server:
  port: 8080
spring:
  application:
    name: kus
  cassandra:
    keyspace-name: url_shortener
    contact-points: localhost
    port: 9042
    local-datacenter: datacenter1
    schema-action: create-if-not-exists
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000
      database: 0

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    doc-expansion: none
  show-actuator: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
