server:
  port: 8080
spring:
  application:
    name: kus
  cassandra:
    keyspace-name: url_shortener
    contact-points: localhost
    port: 9042
    local-datacenter: datacenter1
    schema-action: create-if-not-exists
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000
      database: 0

kus:
  hash:
    algorithm: XXHASH  # Available options: XXHASH, MURMUR3, FNV1A
