version: '3.9'

services:
  cassandra-db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cassandra-db
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_SEEDS=127.0.0.1  # ✅ Ensures it connects to itself
      - CASSANDRA_LISTEN_ADDRESS=127.0.0.1  # ✅ Must match the host machine
      - CASSANDRA_BROADCAST_ADDRESS=127.0.0.1  # ✅ Prevents wrong IP resolution
      - CASSANDRA_BROADCAST_RPC_ADDRESS=127.0.0.1  # ✅ Ensures proper RPC communication
      - CASSANDRA_RPC_ADDRESS=0.0.0.0  # ✅ Allows external connections
      - CASSANDRA_START_RPC=true
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "SELECT now() FROM system.local;"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./data/cassandra:/var/lib/cassandra
      - ./cassandra-init.cql:/cassandra-init.cql
      - ./init-script.sh:/docker-entrypoint-initdb.d/init-script.sh

  redis-cache:
    image: redis:7.2-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
